version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*