version: '3'

services:
  nodejs:
    build:
      context: docker/dev
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3500:3500"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    networks:
      - app-network
    command: /src/node_modules/.bin/nodemon ./dist/server.js

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: