name: CI Pipeline

on:
  push:
    branches:
      - feature/**
      - chore/**
      - bugfix/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn tsc
      - run: yarn lint
      - run: yarn build

      - run: yarn test
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
          CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
          CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          SOCIAL_AUTH_CALLBACK_URL: http://localhost:3500/api/v1/auth/%s/callback
          SOCIAL_AUTH_REDIRECT_URL: http://localhost:3000/dashboard/auth/verify

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
